### ISSUE TITLE
aws-sdk v2 support

### ISSUE THREAD

**Issue by macgregordennis** [lserman/capistrano-elbas#13]

**Comment by macgregordennis** [comment]
@lserman any update on aws-sdk v2 support? I see you mentioned it a few times in the comment history. I was trying to use a gem that depends on aws-sdk v2 and just encountered the conflict.

**Comment by macgregordennis** [comment]
I just noticed that you can use aws-sdk v1 and v2 at the same time, so this isn't actually a problem.

**Comment by lserman** [comment]
Yeah, where we need aws-sdk we use use aws-sdk-v1. Unsure if I'm going to finish v2, we are attempting to move our deployments to ECS which will allow us to stop using Capistrano altogether. We'll see!

**Comment by lserman** [comment]
Closing this, see comments on #20.
