### ISSUE TITLE
Two AutoScale Groups in a Single Deploy, only updates one Launch Config / AMI

### ISSUE THREAD

**Issue by dtirer** [lserman/capistrano-elbas#15]
I have an autoscale group for my workers and one for my application servers:

```
autoscale 'application-box', user: 'deploy', roles: [:app]
autoscale 'worker-box', user: 'deploy', roles: [:worker]
```

However, when I finish my deployment, it only updates the Launch Configuration for one of the Auto Scale groups

**Comment by roccato** [comment]
+1

**Comment by lserman** [comment]
Closing, see comments on #21 and @sixfeetover's fork.
