### ISSUE TITLE
Add command for displaying server public IPs attached to an environment

### ISSUE THREAD

**Issue by lserman** [lserman/capistrano-elbas#17]
Sometimes you need to run `rails c` on your servers or something and it's a pain with an ELB. You don't know the server IPs of your instances without checking the AWS console so you cannot SSH into one of them to run whatever you need to run.

Since elbas has knowledge of your load balancer, environment, and AWS credentials, it would be great if you could run something like `bin/cap production elbas:server_ips` or something to see a list of public IPs (if available) on that environment's ELB.

**Comment by augustosamame** [comment]
+1

**Comment by lserman** [comment]
Duplicate of #33.
