### ISSUE TITLE
Can I separate instance roles?

### ISSUE THREAD

**Issue by cycorld** [lserman/capistrano-elbas#23]
I want to specify the role on the first instance in order to run scheduled works once.

The example is here:
https://github.com/mchicote/capistrano3-autoscaling-deploy#how-this-works

How do you think? 
I wish you develop this function soon or I can help you to implement it.

**Comment by frederikspang** [comment]
Would also be great for migrations, if you're only running one scale-group as your server. Wouldn't db:migrate run on them all? (I haven't tried yet - Just setting this gem up for the first time).

**Comment by lserman** [comment]
Fixed in 3.0.2 via bf38a877737dbc31700b10c17526297d95e14284
