### ISSUE TITLE
Gem doesn't support simultaneous deployment to more than one autoscale group.

### ISSUE THREAD

**Issue by macgregordennis** [lserman/capistrano-elbas#4]

**Comment by macgregordennis** [comment]
When deploying to a second autoscale group, this occurs:

![screen shot 2015-10-04 at 5 07 28 pm](https://cloud.githubusercontent.com/assets/1322709/10271100/83a667ee-6aba-11e5-9ca1-9e6e8832ca9d.png)

I think this is because the deploy script for one autoscale group is attempting to delete the launch configuration for the other autoscale group. I think that this could happen with the AMIs too.

**Comment by lserman** [comment]
I'm open to ideas on how to cleanly tag AMIs/LCs so that the deployment knows which ones to remove at the end of the run. Right now we simply check that the name contains "ELBAS" and the environment. I suppose we could tag them somehow with the name of the autoscale group instead.

**Comment by macgregordennis** [comment]
> I'm open to ideas on how to cleanly tag AMIs/LCs so that the deployment knows which ones to remove at the end of the run. 

Great.

> I suppose we could tag them somehow with the name of the autoscale group instead.

I had the same idea. I think we need to update these lines:
* https://github.com/turinginc/capistrano-elbas/blob/master/lib/elbas/launch_configuration.rb#L32
* https://github.com/turinginc/capistrano-elbas/blob/master/lib/elbas/launch_configuration.rb#L54
* https://github.com/turinginc/capistrano-elbas/blob/master/lib/elbas/ami.rb#L32

I'm trying to get something working at the moment.

**Comment by lserman** [comment]
Name is probably fine, we probably just need to change the `deployed_with_elbas?` method to look for whatever identifier is decided on. I think the cleanest thing would be to remove the overridden version of `deployed_with_elbas?` in LaunchConfiguration, and instead just change the one in AWSResource to work for both AMI and the LC.

I remember changing the AWSResource version to use tags instead of the name, can't remember why I had to override for the LC... I think it might be because LCs don't support tagging? I'd have to look again, it's been awhile. It would be ideal to just check a tag on either resource though so that it is consistent for both resources. And instead of tagging the AMI with just Deployed-With=ELBAS, we can tag with Deployed-With=<Autoscale Group Name>.

:+1:

**Comment by macgregordennis** [comment]
Agreed.

How about something along the lines of this:

```ruby
module Elbas
  class AWSResource

    private

      def deployed_with_elbas?(resource)
        resource.tags['Deployed-with'] == 'ELBAS' && resource.tags['Autoscale-group-name'] == autoscale_group_name
      end

  end

  class LaunchConfiguration < AWSResource

    private

      def name
        timestamp "ELBAS-#{environment}-#{autoscale_group_name}-LC"
      end

      def deployed_with_elbas?(lc)
        lc.name =~ /ELBAS-#{environment}-#{autoscale_group_name}/
      end

  end

  class AMI < AWSResource
    include Taggable

    def self.create(&block)
      ami = new
      ami.cleanup do
        ami.save
        ami.tag 'Deployed-with' => 'ELBAS'
        ami.tag 'Autoscale-group-name' => autoscale_group_name
        yield ami
      end
    end

  end
end
```

Some quick comments:
* I just tested this and it works.
* I'm not sure why you implemented the LC elbas detection mechanism in a different way either, but I'm assuming that you had some reason so I haven't attempted to unify the mechanisms here.
* I added a separate tag for the autoscale group name because this seemed like a separate data point and it could be useful to get all resources that have been deployed with ELBAS at some point (and this would allow doing so without regex/string parsing).
* If this looks good, I can make the changes properly in the forked repo and submit a PR.

Do you have any feedback on the above?

**Comment by lserman** [comment]
Looks good. Thanks. I will look into unifying it later. I was going to hop into this project again soon anyway so I can update it to aws-sdk 2.

**Comment by macgregordennis** [comment]
Awesome. That all sounds great.
